### ISSUE TITLE
Non-default argument follows default argument syntax error

### ISSUE THREAD

**Issue by z-w123** [nadimm-rahman/ena-read-validator#5]
When running the following command: "python3 read_validator_4.py -s read_validator_test_spreadsheet.xlsx -g genome -u Webin-55868 -p '#####' -m submit -t" the following error is thrown:

line 114
def webin_cli_validate_submit(WEBIN_USERNAME, WEBIN_PASSWORD, manifest_file, context, mode, upload_file_dir="", center_name="", test):
                                  ^
SyntaxError: non-default argument follows default argument

**Comment by nadimm-rahman** [comment]
Issue has been fixed, all non-default arguments were moved to the end of the def statement.
